# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sm < Formula
  desc "AWS Secrets Manager CLI Tool"
  homepage "https://clokwork.net/sm/"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clok/sm/releases/download/v0.1.1/sm_0.1.1_darwin_amd64.tar.gz"
      sha256 "9f4559fa531e11529034584d3c7c9d7d11ff90af719f2121bc3c8d9446071709"

      def install
        bin.install "sm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clok/sm/releases/download/v0.1.1/sm_0.1.1_darwin_arm64.tar.gz"
      sha256 "9c67a217ee56c536db934fde0e335901a2f3df59f643d8cc464e567118577ea1"

      def install
        bin.install "sm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/clok/sm/releases/download/v0.1.1/sm_0.1.1_linux_armv6.tar.gz"
      sha256 "6dc3fc57b3e3f6a155ac1491e944cbf3c5b4faf2263bf84f94410c4d473c118f"

      def install
        bin.install "sm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clok/sm/releases/download/v0.1.1/sm_0.1.1_linux_amd64.tar.gz"
      sha256 "6b56e32ab9480c05ce8e4b8e296d7d00bca3be98e740144cb602fe5539428baa"

      def install
        bin.install "sm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clok/sm/releases/download/v0.1.1/sm_0.1.1_linux_arm64.tar.gz"
      sha256 "62e2ad697939132d1541c7081c1340e289aa4d0c339961813202a83ffadd3142"

      def install
        bin.install "sm"
      end
    end
  end

  test do
    system "#{bin}/sm --help"
  end
end
