# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sm < Formula
  desc "AWS Secrets Manager CLI Tool"
  homepage "https://clokwork.net/sm/"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clok/sm/releases/download/v0.1.0/sm_0.1.0_darwin_amd64.tar.gz"
      sha256 "3999c2c7e197314e08e1e763fbfe877d27470818d284c4a6b7bc242ca175c5df"
    end
    if Hardware::CPU.arm?
      url "https://github.com/clok/sm/releases/download/v0.1.0/sm_0.1.0_darwin_arm64.tar.gz"
      sha256 "0617fc6274821109f713707aecbd8ecb5db08e51599e8c2c1125eaae7e57cd20"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/clok/sm/releases/download/v0.1.0/sm_0.1.0_linux_amd64.tar.gz"
      sha256 "e6100579c9267e5a59a64b58c61bd8612bac22092c9acd0993bfc14121a3d6aa"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/clok/sm/releases/download/v0.1.0/sm_0.1.0_linux_armv6.tar.gz"
      sha256 "cfd5247c9c8bb55eedfcfe3f2e45bf98863f6137c43dbb758cb7a871f5857bce"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clok/sm/releases/download/v0.1.0/sm_0.1.0_linux_arm64.tar.gz"
      sha256 "81ed516d6f21a4ad4621d3910b59b82834b79d9b8a6ef9e1de94109e288d52e5"
    end
  end

  def install
    bin.install "sm"
  end

  test do
    system "#{bin}/sm --help"
  end
end
